version: 2.1

jobs:
  test:
    docker:
      - image: circleci/clojure:lein-2.9.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: lein deps
      - run:
          name: Run tests
          command: lein test

workflows:
  version: 2
  test:
    jobs:
      - test